### ISSUE TITLE
onGetContentElement requires ContentModel

### ISSUE THREAD

**Issue by richardhj** [codefog/contao-haste#105]
Your [`onGetContentElement`](https://github.com/codefog/contao-haste/blob/master/library/Haste/EventListener/AjaxReloadListener.php#L22) wants argument 1 to be a `ContentModel`. However, I use a custom model, which indeed uses the functionality of `tl_content` but is no child of `ContentModel`.

For instance, I use `Controller::getContentElement()` for my purposes, using my custom model, causing the following error:
```
Fatal error: Uncaught exception TypeError with message Argument 1 passed to Haste\EventListener\AjaxReloadListener::onGetContentElement() must be an instance of Contao\ContentModel, instance of EPost\Model\LetterContent given, called in /Users/richard/Sites/sjr-beta/system/modules/core/library/Contao/Controller.php on line 491 thrown in composer/vendor/codefog/contao-haste/library/Haste/EventListener/AjaxReloadListener.php on line 22
#0 system/modules/core/library/Contao/Controller.php(491): Haste\EventListener\AjaxReloadListener->onGetContentElement(Object(EPost\Model\LetterContent), '\n
```

**Comment by qzminski** [comment]
Does your model extend `\Contao\Model`? I am not sure if we should change that though because Contao should expect `ContentModel` by default. @Toflar @aschempp

**Comment by richardhj** [comment]
> Does your model extend \Contao\Model?

Exactly.

**Comment by Toflar** [comment]
It must extend `ContentModel`. There are many, many other places where this code would fail otherwise (e.g. the `isVisibleElement` hook where you **MUST** check for an instance of content element or front end module). So nothing to do here imho.

**Comment by qzminski** [comment]
Yup, I think so too. @richardhj I suggest that you extend `ContentModel` and have some method that works as a proxy for all the stuff you currently have in your custom model.
