### ISSUE TITLE
FR: Util/Url - trigger disableAlias or set parameter to use '/' as separator

### ISSUE THREAD

**Issue by zonky2** [codefog/contao-haste#107]
the "most URL builder" trigger the `$GLOBALS['TL_CONFIG']['disableAlias']` to change the separator from `&amp;%s=%s` to `/%s/%s`

e.g. 
https://github.com/contao/core/blob/af729dcc8c72df338ecf8e3e216aa88706d9a3b9/system/modules/core/classes/Frontend.php#L378

https://github.com/MetaModels/core/blob/master/src/MetaModels/FrontendIntegration/FrontendFilter.php#L92

may be, its a good feature to add this trigger or add a additional parameter ... and we can see the URL like `...my-mp_form/step/1.html` at "mp_forms"

**Comment by qzminski** [comment]
Pull requests are welcome 😉

**Comment by zonky2** [comment]
o.k. - we´ll use the trigger or an additional parameter?

**Comment by qzminski** [comment]
I suggest that you create another method (e.g. `addPathString`) because the current ones refer explicitly to the query string.

**Comment by zonky2** [comment]
o.k. ...

**Comment by qzminski** [comment]
Any news on this @zonky2 ?
