### ISSUE TITLE
Support adding dca fields from a palette

### ISSUE THREAD

**Issue by dmolineus** [codefog/contao-haste#108]
I often use a custom palette in my dca to define the frontend form palette. It would be nice if Haste would support it out of the box to get the dca fields from a dca palette. Each legend would be rendered as a fieldset.

```php
$form->addFieldsFromDcaPalette($table, $palette, $callback);
```
If you agree to add it I would prepare a PR for it.

**Comment by qzminski** [comment]
Sure, go ahead!

**Comment by zonky2** [comment]
@dmolineus PR? ;-)

**Comment by dmolineus** [comment]
@zonky2 It's on my todo list.

**Comment by qzminski** [comment]
Any news on this @dmolineus ?
