### ISSUE TITLE
Saving Event startTime / endTime correct

### ISSUE THREAD

**Issue by SGehle** [codefog/contao-haste#111]
There is a problem with an event, using $objForm->bindModel().
The Date of the Timestamp for startTime / endTime is 01/01/1970 instead of startTime / endTime Date.
My workaround:

`if($objEvent->startTime) {
$objEvent->startTime = strtotime(date('Y-m-d', $objEvent->startDate). " ".date('H:i', $objEvent->startTime));
}`

**Comment by qzminski** [comment]
That is not a bug but a special way the Contao handles the event date saving, so it is correct to use custom code here. https://github.com/contao/core/blob/master/system/modules/calendar/dca/tl_calendar_events.php#L849
