### ISSUE TITLE
Error finding Class 'DateRangeFilter'

### ISSUE THREAD

**Issue by SGehle** [codefog/contao-haste#112]
After installing Haste, the following error is shown in Contao Manager when clearing cache:

Warning: in_array() expects parameter 2 to be array, null given in /homepages/15/d697471085/htdocs/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 169
15:40:50 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'Haste\Dca\DateRangeFilter' not found" ["error" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'Haste\Dca\DateRangeFilter' not found"] []

                                                                         
  [Symfony\Component\Debug\Exception\ClassNotFoundException]             
  Attempted to load class "DateRangeFilter" from namespace "Haste\Dca".  
  Did you forget a "use" statement for another namespace?                
                                                                         

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

--------------------------------------------------------
Exception occured: The command "/usr/bin/php7.0-cli '-q' '-d' 'memory_limit=-1' '/homepages/15/d697471085/htdocs/contao/vendor/bin/contao-console' 'cache:warmup' '--env=prod'" failed.

Exit Code: 255(Unknown error)

Working directory: /homepages/15/d697471085/htdocs/contao

Output:
================

 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

Warning: in_array() expects parameter 2 to be array, null given in /homepages/15/d697471085/htdocs/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 169

Error Output:
================
15:40:50 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'Haste\Dca\DateRangeFilter' not found" ["error" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'Haste\Dca\DateRangeFilter' not found"] []

                                                                         
  [Symfony\Component\Debug\Exception\ClassNotFoundException]             
  Attempted to load class "DateRangeFilter" from namespace "Haste\Dca".  
  Did you forget a "use" statement for another namespace?                
                                                                         

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

#0 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/api/Tenside/Task/RebuildCacheTask.php(86): Tenside\Core\Task\AbstractCliSpawningTask->runProcess(Object(Symfony\Component\Process\Process))
#1 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/api/Tenside/Task/RebuildCacheTask.php(52): Contao\ManagerApi\Tenside\Task\RebuildCacheTask->runSymfonyCommand('cache:warmup')
#2 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Contao\ManagerApi\Tenside\Task\RebuildCacheTask->doPerform()
#3 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/homepages/15/d...')
#4 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/homepages/15/d...')
#5 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /homepages/15/d697471085/htdocs/contao/web/contao-manager.phar.php(55): require('phar:///homepag...')
#13 {main}
--------------------------------------------------------

Process terminated with exit code 1
Reason: General error

**Comment by SGehle** [comment]
NamespaceClassLoader was missing.

**Comment by Aybee** [comment]
The same with Contao 3.5.29 without composer. The _autoload extension - system/modules/_autoload/ must not be deactivated. NamespaceClassLoader.php is in there.
