### ISSUE TITLE
Default value after Ajax reload

### ISSUE THREAD

**Issue by kehr-solutions** [codefog/contao-haste#113]
Nach einem ajax-reload vom Formular werden die default-Werte leider nicht mehr gesetzt.
```
$objForm->addFormField(
            'lang',
            [
                'label'     => 'Label',
                'default'   => 3,
                'inputType' => 'select',
                'options'   => [1 => 'Sprache 1', 2 => 'Sprache 2', 3 => 'Sprache 3'],
            ]
        );
```

für ajax-reload wird folgende Erweiterung verwendet.
[richardhj/contao-ajax_reload_element](https://github.com/richardhj/contao-ajax_reload_element)

**Comment by qzminski** [comment]
I don't think this a Haste related issue. The form sets the value based on the `$_POST` data and if no data is given, then the default value is used. So logically thinking there already must be some data sent for that field in the AJAX request. Check the headers that are sent with the XHR and you will know what's the problem.

**Comment by kehr-solutions** [comment]
Hier ist die Feld definition
```
$objForm->addFormField(
            'spl_lang',
            [
                'label'     => 'Label',
                'default'   => \Contao\Input::post('spl_lang'),
                'inputType' => 'select',
                'options'   => [1 => 'Sprache 1', 2 => 'Sprache 2', 3 => 'Sprache 3'],
            ]
        );

```
Der Header sieht folgendermaßen aus
![haste-ajax](https://user-images.githubusercontent.com/17803079/32097628-71d7c1e6-bb0a-11e7-99cf-d4b5999d0f47.jpg)

wenn ich mir die \Contao\Input::post('spl_lang') ausgebe, erhalte ich auch den gewählten Wert von 3
