### ISSUE TITLE
http_build_query wrong arguments seperator

### ISSUE THREAD

**Issue by koertho** [codefog/contao-haste#116]
Some Hoster (for example Host Europe) returning a wrong default argument seperator for http_build_query function. So please change the function call from `http_build_query(array_merge($queries, $new));` to `http_build_query(array_merge($queries, $new),'', '&');`.
For example here: 
https://github.com/codefog/contao-haste/blob/966cd2e4cbf3236cef868ee67aff394188eedf5e/library/Haste/Util/Url.php#L43

**Comment by qzminski** [comment]
That's interesting, thanks for reporting.

**Comment by Toflar** [comment]
You should always pass it, I've stumbled over similar stuff, very annoying :)

**Comment by qzminski** [comment]
Fixed in 1475f7a.

**Comment by koertho** [comment]
That was quick, thanks!
