### ISSUE TITLE
Use SUBMIT_TYPE = auto in Form.php

### ISSUE THREAD

**Issue by SGehle** [codefog/contao-haste#117]
Would it be possible to add the SUBMIT_TYPE = auto in Form.php like it is used in https://github.com/contao/core/issues/4077

// Skip mandatory fields on auto-submit (see #4077)
if (\Input::post('SUBMIT_TYPE') != 'auto' || !$objWidget->mandatory || $objWidget->value != '')

**Comment by qzminski** [comment]
I don't see any practical use case for this. That stuff relates to **backend** and it's very specific to DCA. If you need it in your **frontend** implementation you can always create your own class that extends `Form` and override appropriate methods.

**Comment by SGehle** [comment]
Yes, i use it that way.
My usecase is having different Isotope ProductTypes in a form with different mandatory fields.
