### ISSUE TITLE
do not hard code MyISAM and utf8_general_ci (for Contao 4)

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-haste#120]
Contao 4.5 fully supports `utf8mb4` and `InnoDB` now. The default database collation and character set are set as such. However, Haste still hardcodes this when using relations. See https://github.com/codefog/contao-news_categories/issues/125 for instance.

**Comment by m-vo** [comment]
see #119

**Comment by Toflar** [comment]
See https://github.com/codefog/contao-haste/pull/119 and help us in the discussion there :)

**Comment by fritzmg** [comment]
Ah, didn't bother to look at existing PRs, sorry ;)
