### ISSUE TITLE
FR: add new form fields after/before existing ones

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-haste#130]
Use case: https://github.com/1up-lab/contao-mailchimp/pull/18 :)

Currently I have to remove form fields altogether in order to insert something before them in an existing form. For the linked event it would be handy if you could define if a form field should be added before or after a specific other form field.

**Comment by Toflar** [comment]
Why? Did you use `addFormField()`? You can pass an instance of `ArrayPosition` and even give that a name 😄

**Comment by fritzmg** [comment]
Haha, oops 😁
