### ISSUE TITLE
non-existing runonce

### ISSUE THREAD

**Issue by zonky2** [codefog/contao-haste#134]
C 3.5.35, Haste 4.20.3

after "new synchronisation" at package manager I found

```Skip non-existing runonce composer/vendor/codefog/contao-haste/system/modules/haste/config/upgrade.php```

the path is

```composer/vendor/codefog/contao-haste/config/upgrade.php```

**Comment by aschempp** [comment]
Fixed in 0c250dfc016557896d7a1b82beb22b8fcf69e58b
