### ISSUE TITLE
Haste does not execute the onundo_callback

### ISSUE THREAD

**Issue by dmolineus** [codefog/contao-haste#156]
When a project uses haste, the `onundo_callback` is never called. Every extension using is broken now.

**Comment by qzminski** [comment]
Maybe I'm missing something, but how is `onundo_callback` related to Haste? And why every extension is broken?

**Comment by dmolineus** [comment]
Haste modifies the undo button in the `tl_undo` dca, so not the undo action of the DC_Table is triggered but the undo feature of haste.

**Comment by qzminski** [comment]
Can you try 112e63b2 before I release a new version please?

**Comment by dmolineus** [comment]
Looks good

**Comment by qzminski** [comment]
Thanks, should be there in 4.24.11 :+1:

**Comment by dmolineus** [comment]
Thanks for the fast fix
