### ISSUE TITLE
PHP8 compat

### ISSUE THREAD

**Issue by m-vo** [codefog/contao-haste#158]
Is PHP 8 compat planned for this bundle?
Probably only needs a widened constraint.

**Comment by m-vo** [comment]
OK, not quite. There are array access issues as well.

----
one is here

`Warning: Undefined array key "exclude"` in
https://github.com/codefog/contao-haste/blob/8229b8000bf114e2502083030d698513beaebb01/library/Haste/Dca/AjaxOperations.php#L189

**Comment by qzminski** [comment]
We haven't had a chance to test it under PHP 8 yet. Pull requests are very much welcome.

**Comment by m-vo** [comment]
Closing in favor of #160
