### ISSUE TITLE
Filter for many-to-many relations not visible

### ISSUE THREAD

**Issue by dmolineus** [codefog/contao-haste#162]
Since https://github.com/codefog/contao-haste/pull/161 the filter for many-to-many related fields are not added to the panel anymore. Issue is caused in this line:

https://github.com/codefog/contao-haste/blob/f6ece9e5a2aafd479b85aa4d683d185d1ebce06d/library/Haste/Model/Relations.php#L113

The correct check has to be:

```diff
-            if (isset($GLOBALS['TL_DCA'][$strTable]['list']['panelLayout'])){
+            if (isset($GLOBALS['TL_DCA'][$strTable]['list']['sorting']['panelLayout'])){
```

/cc @rabauss

**Comment by qzminski** [comment]
Good catch, should be fixed now.

**Comment by rabauss** [comment]
Oh damn it, I copied the wrong array keys 😢
