### ISSUE TITLE
Exclude tests/ from distribution

### ISSUE THREAD

**Issue by ameotoko** [codefog/contao-haste#164]
Can you please exclude tests directory from installing in production? The declarations in `bootstrap.php` ruin the IntelliSense for Contao classes.

**Comment by aschempp** [comment]
you have to mark the folder as "excluded" in PHPStorm to not make it load the classes.

**Comment by ameotoko** [comment]
PHPStorm does not let me do that from context menu in `vendor/` directory, and it is already excluded in "Preferences -> Dirctories". And I would have to do it manually in each project. Why? I am not ever going to run those tests, it is not even a direct dependency of my project, I did not require it.

Much better way is to prevent it from installing in `prod` environment by using few lines in your `.gitattributes`, e. g. like Contao does it:

```gitattributes
/.github export-ignore
/.gitattributes export-ignore
/tests export-ignore
/phpunit.xml.dist export-ignore
```

**Comment by fritzmg** [comment]
> Much better way is to prevent it from installing in `prod` environment by using few lines in your `.gitattributes`, e. g. like Contao does it:

Just provide a PR for that ;)

**Comment by aschempp** [comment]
Closed in favour of https://github.com/codefog/contao-haste/pull/165
