### ISSUE TITLE
Form validation leads to data container type errors in save_callbacks for tl_calendar_events

### ISSUE THREAD

**Issue by Defcon0** [codefog/contao-haste#184]
Hello,

I recently used the Form class which works great so far. Only one thing isn't quite perfect. When using the validate() function, the save_callback of the field endTime (data container tl_calendar_events) tl_calendar_events::setEmptyEndTime() is called out of the Form class.

Unfortunately, this callback has a type hin which is `DataContainer $dc` and the Form class passes in a stdClass. Therefor I get type hint errors.

https://github.com/codefog/contao-haste/blob/main/src/Form/Form.php#L373-L380

I suspect that the reason for this is that by creating a DC_Table instance, callbacks would be called without intention (onload_callback e.g.).

Is there any way to cope with that problem?

Thanks in advance!

bye Defcon0

**Comment by qzminski** [comment]
I don't think there is a good way to handle this, as data container objects are backend dependent and have some request handling built inside (redirects, URL parameter reads/writes, etc). We tried to provide a data container mockup back in the days which worked most of the times, but it's time to revisit this workaround.

I see two possible outcomes here:

1. Provide a class that extends `DataContainer` but does not do anything apart from providing the necessary objects like `$dc->id` or `$dc->activeRecord`. This would probably work in most of the cases.
2. Remove all the DCA callbacks from the form fields before loading them into the form.

@Toflar @aschempp what do you think?

**Comment by Toflar** [comment]
It's a common problem which is due to a few architectural design issues. I think we can provide a Datacontainer mock which would help, yes. I'm also doing this in the next iteration of mp_forms. Thanks to anonymous classes, it's pretty easy: https://github.com/terminal42/contao-mp_forms/blob/develop/src/FormManager.php#L271

**Comment by qzminski** [comment]
I have created a pull request that should fix this: https://github.com/codefog/contao-haste/pull/185

@Defcon0 would you be able to test it out for me?
