### ISSUE TITLE
5.x Insert tags are not working

### ISSUE THREAD

**Issue by dmolineus** [codefog/contao-haste#186]
The insert tags provided by haste are not working. It seems like that the `InsertTagListener` is not registered anywhere, see [contao-haste](https://github.com/codefog/contao-haste)/[config](https://github.com/codefog/contao-haste/tree/main/config)/[services.yml](https://github.com/codefog/contao-haste/tree/main/config/services.yml)

//cc @frontendschlampe

**Comment by qzminski** [comment]
Thanks, should be fixed in 5.0.6.
