### ISSUE TITLE
[v5] Relation tables are deleted while contao:migrate

### ISSUE THREAD

**Issue by rabauss** [codefog/contao-haste#187]
In a project we have defined some custom entities with many-to-many relations like this:
```php
// contao/dca/tl_taxonomy.php
'relation' => [
    'type' => 'haste-ManyToMany',
    'load' => 'lazy',
    'table' => 'tl_content_teaser',
],
```

After upgrading to Haste v5 the command `contao:migrate` deletes all relation tables (e.g. `DROP TABLE tl_content_teaser_taxonomy`).
In the contao install tool the deletions are not listed/executed only via console command!
Our app bundle is loaded after `CodefogHasteBundle`!

What's the reason for this misbehavior? Is there a framework init missing?

**Comment by aschempp** [comment]
that looks very weird, why would relations be tied to the request? 🤔

**Comment by rabauss** [comment]
Well, this was migrated from this logic:
https://github.com/codefog/contao-haste/blob/f5de7fd1b13fa9afce41dc466860918dc40eb13b/config/config.php#L39

I'm not sure if the hook `sqlGetFromFile` even needs this restriction on backend

**Comment by fritzmg** [comment]
Yeah, this needs to be changed to:

```php
if (!$request || !$this->scopeMatcher->isFrontendRequest($request)) { 
```

**Comment by rabauss** [comment]
Ok, I'll add a PR

**Comment by qzminski** [comment]
I think we should not check for request at all. This was legacy stuff in Contao 3.
