### ISSUE TITLE
Incorrect parameter count in the call to native function 'FIND_IN_SET'

### ISSUE THREAD

**Issue by argus231** [codefog/contao-haste#193]
vendor/codefog/contao-haste/src/Model/DcaRelationsModel.php

152&127 -> $order = ' ORDER BY FIND_IN_SET('.$connection->quoteIdentifier($relation['reference_field']).', '.implode(',', $recordValues).')';

wrong -> ORDER BY FIND_IN_SET(`xxx`, 125,18,279,5785,50730)
correct ->  ORDER BY FIND_IN_SET(`xxx`, "125,18,279,5785,50730")

**Comment by qzminski** [comment]
@argus231 could you test and confirm if https://github.com/codefog/contao-haste/commit/f3a693757fcbd54b4f82a176a80f99d15b81e77d solves the problem?

**Comment by qzminski** [comment]
Thanks for testing, I have just released 5.0.12.
