### ISSUE TITLE
4.X | Image:addWatermark() fails in PHP8

### ISSUE THREAD

**Issue by cboelter** [codefog/contao-haste#194]
I'm currently working on an isotope shop which is using the watermark feature. This feature relies on the haste `Image::addWatermark()` function. In Line 123 it contains a check that `$resWatermark` is a resource. 
Since PHP8 the `$resWatermark` could also be an instance of `GDImage`. Is it possible to be fixed in the haste 4.X?

**Comment by aschempp** [comment]
I'm sure if you do a pull request we can merge it 😊

**Comment by aschempp** [comment]
fixed in 2388687f9d14fad01cbf57a6b50eb519d44fcb63
