### ISSUE TITLE
Missing `rt` parameter in Contao's Dashboard when using Haste's toggle operation

### ISSUE THREAD

**Issue by fiedsch** [codefog/contao-haste#201]
When using ` 'haste_ajax_operation' => [ ... ]` as described in the [docs](https://github.com/codefog/contao-haste/blob/main/docs/DcaAjaxOperations.md) toggling works as expected. But when inspecting the change in Contao's Dashboard the `rt=...` parameter is missing which causes an "invalid token" warning.

When performing the toggle with Contao core features (also as described in the docs) there is no missing `rt` parameter.

I originally found this with haste `^4.25`, Contao 3.14 and PHP 8.1, but could also reproduce it with the current haste `^5.0` (and Contrao 4.13 with PHP 8.2).

If anybody could give me a hint where to start debugging, I'd be happy to help. For the moment, I'm lost :-(

**Comment by qzminski** [comment]
Fixed in https://github.com/codefog/contao-haste/commit/3d31451d567acd3d5cfe2e2af9755c9f93f62326. Please update to 5.0.16.
