### ISSUE TITLE
[FORM] Removing inline event listeners

### ISSUE THREAD

**Issue by doishub** [codefog/contao-haste#206]
I noticed that when I output a form via `addFieldsFromDca` in the frontend, I still get inline events for the backend delivered with it.

```html
<select ... onchange="Backend.autoSubmit('tl_mytable')">
```

Is there already a way to remove attributes from the widget when the fields are built via the `addFieldsFromDca`?

**Comment by qzminski** [comment]
I think there is no automatic way to remove all backend listeners at once. However, we could maybe unset `$arrData['eval']['submitOnChange']` before the form field is processed.

@Toflar @aschempp what do you think?

**Comment by Toflar** [comment]
Yeah, makes no sense in the FE. There are always going to be hacks like that as the DCA is just not meant to be used in the FE ;)

**Comment by qzminski** [comment]
But what would be the best way to strip this and others you think?

**Comment by Toflar** [comment]
Just remove `submitOnChange`, yes. It has no effect in the FE so remove it.

**Comment by qzminski** [comment]
@doishub can you try my fix [93dcdb9](https://github.com/codefog/contao-haste/commit/93dcdb9043219fbff9e436268a5272e3258b968a) ?

**Comment by doishub** [comment]
Works 👍

**Comment by qzminski** [comment]
Great! Please update to 5.1.2 stable.
