### ISSUE TITLE
Uncaught PHP Exception TypeError

### ISSUE THREAD

**Issue by christianbarkowsky** [codefog/contao-haste#207]
Haste version: 5.1.2
Contao: 4.13.16
PHP: 8.1 & 8.2

`Uncaught PHP Exception TypeError: "Codefog\HasteBundle\EventListener\AjaxReloadListener::onGetFrontendModule(): Argument #2 ($buffer) must be of type string, null given, called in /htdocs/cto2022/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php on line 447" at /htdocs/cto2022/vendor/codefog/contao-haste/src/EventListener/AjaxReloadListener.php line 45 {"exception":"[object] (TypeError(code: 0): Codefog\\HasteBundle\\EventListener\\AjaxReloadListener::onGetFrontendModule(): Argument #2 ($buffer) must be of type string, null given, called in /htdocs/cto2022/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php on line 447 at /htdocs/cto2022/vendor/codefog/contao-haste/src/EventListener/AjaxReloadListener.php:45)"} []`

**Comment by fritzmg** [comment]
This is a follow-up error, caused by another extension that returns `null` instead of a string in a `getFrontendModule`. You need to analyse the `getFrontendModule` hooks in your Contao instance.

**Comment by christianbarkowsky** [comment]
The problem was a 5 years not updated extension.
Sorry for the hasty issue.

**Comment by jankout** [comment]
Hello, unfortunately, I have this error too but I cannot figure it out which extension causes this problem. Do you have any useful tip how to figure it out?
