### ISSUE TITLE
Function "setAction" or "setActionFromPageId" not working (PHP 8.2 / Contao 5.2)

### ISSUE THREAD

**Issue by jaynoe** [codefog/contao-haste#215]
I created a FrontendModule Controller, where i build a custom form via the Form-Builder. Now i want to change the `action` value - but nothing happens. Here is the part of the code:

```php
$form = new Form('donation_form_'.$model->id, 'POST');
$form->setActionFromPageId = PageModel::findById($model->jumpTo)->id;
$form->addContaoHiddenFields();
$form->addCaptchaFormField();
```
Also in PHP 8.2 you get a deprecated notice by using the `setAction:` or `setActionFromPageId`  function:
`Property declared dynamically, this is deprecated starting from PHP 8.2 `

But i guess the functions should work despite the deprecated note. Also you can [set a attribute](https://php.watch/versions/8.2/dynamic-properties-deprecated#exempt) to prevent the notice - just for information

**Comment by qzminski** [comment]
You should use a function like described here: https://github.com/codefog/contao-haste/blob/main/docs/Form.md#preparing-a-form-instance

```php
$form->setActionFromPageId($model->jumpTo);
```

**Comment by jaynoe** [comment]
Yeah, i was following the guide. I changed it now to `$form->setActionFromPageId = $model->jumpTo` but the action is still the initial request uri.

Nevermind its working now, dont know why - i changed it to this:
```php
form->setAction(PageModel::findById($model->jumpTo)->getFrontendUrl());
```

**Comment by qzminski** [comment]
It did not work because you tried to assign a non-existing property instead of using a function:

```php
$form->setActionFromPageId = PageModel::findById($model->jumpTo)->id;
```

should become:

```php
$form->setActionFromPageId(PageModel::findById($model->jumpTo)->id);
```

and even better:

```php
$form->setActionFromPageId($model->jumpTo);
```
