### ISSUE TITLE
Missing dependency on `symfony/security-core`

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-haste#223]
There is a missing dependency on `symfony/security-core: ^5.4 || ^6.4` in version 5 causing the following error in Contao 5.4+:

```
Cannot autowire service "Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener": argument "$security" of method "__construct()" has type "Symfony\Component\Security\Core\Security" but this class was not found.
```

This is because `Symfony\Component\Security\Core\Security` does not exist in Symfony 7 anymore.

Furthermore, if you downgrade `symfony/security-core` to version `6.4.*` the following error will occur:

```
Cannot autowire service "Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener": argument "$security" of method "__construct()" references class "Symfony\Component\Security\Core\Security" but no such service exists. Try changing the type-hint to "Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface" instead.
```

Not sure how to fix the former properly though. Adding the missing dependency will still allow a dependency result set that is broken.

**Comment by qzminski** [comment]
@aschempp @Toflar

**Comment by Toflar** [comment]
I think requiring `symfony/security-core` in `^6.2 || ^7.0` and type-hinting to `Symfony\Bundle\SecurityBundle\Security` instead, should fix the issue?

**Comment by fritzmg** [comment]
That would remove compatibility with Contao 4.13 though.

**Comment by Toflar** [comment]
Right. Then somebody has to come up with a solution because I don't have one.

**Comment by fritzmg** [comment]
I think the easiest would be to remove the type and inject the dependency without auto wiring, while also adding the dependency for Symfony 5, 6 and 7. I will create a PR after my (second) vacation.

**Comment by fritzmg** [comment]
Closing in favor of #225.
