### ISSUE TITLE
Fehler bei gleichzeitiger Verwendung von EFG

### ISSUE THREAD

**Issue by Total-Reality** [codefog/contao-haste#59]
Wenn man im Contao Backend unter "Feedback" einen Eintrag löschen will, erhält man die Fehlermeldung:

Fatal error: Cannot redeclare class tl_fd_feedback in ......./system/modules/efg/dca/fd_feedback.php on line 731

Das ganze passiert nicht, wenn "haste" nicht aktiviert ist.

**Comment by Toflar** [comment]
Hat mit haste aber bestimmt nichts zu tun. Bitte beim efg melden.

**Comment by Total-Reality** [comment]
Nun, ich glaube das bringt nichts. Die Erweiterung "efg" gibt es aber schon ewig, daher sollte man der Sache vielleicht trotzdem auf den Grund gehen?
Denn ich weiß nicht, ob Thomas Kuhn die Erweiterung "haste" überhaupt kennt, geschweigedenn testweise intallieren wird.

Ich konnte die Sache nun genauer eingrenzen. Wenn ich in /haste/library/Haste/Model/Relations.php die Zeile 78 auskommentiere, funktioniert alles wieder.

$GLOBALS['TL_DCA'][$strTable]['config']['ondelete_callback'][] = array('Haste\Model\Relations', 'cleanRelatedRecords');

Danach habe ich genauer geprüft woran es liegt. Die Funktion cleanRelatedRecords() ruft in Zeile 303 die Funktion $this->loadDataContainers(); auf.

Hier werden nach und nach alle Namen der dca-files ausgelesen. Es wäre am besten, wenn ihr Dateien ignorieren würdet, die nicht mit tl_ anfangen. Oder woran liegt das?

Haste hat jedenfalls mit der EFG-Datei fd_feedback.php im system/modules/efg/dca/ so seine Probleme. In der betroffenen Datei steht folgendes:

class tl_fd_feedback extends \Backend
{
...
}

Wenn ich testweise die Zeile 236 in /haste/library/Haste/Model/Relations.php auskommentiere, gibt es auch keine Fehler mehr:
Haste::getInstance()->call('loadDataContainer', substr($strFile, 0, -4));

**Comment by aschempp** [comment]
Das Problem ist doch, dass der EFG nicht dem Contao-Standard folgt. Wir müssten ja für jede Erweiterung eine Ausnahme machen, bei welcher der Entwickler "etwas bastelt". Bei EFG ist das historisch bedingt weil es früher nicht anders ging, aber halt nie angepasst wurde…

**Comment by Total-Reality** [comment]
Mal aus eigenem Interesse, weil ich auch Erweiterungen erstelle. Was genau ist denn das Problem? Darf man in den DCA-Files keine Klassen schreiben oder liegt es daran, dass eine DCA-File existiert (fd_feedback.php), die es nicht als SQL-Tabelle gibt?
