### ISSUE TITLE
Fix the addFieldsFromDca() method

### ISSUE THREAD

**Issue by qzminski** [codefog/contao-haste#61]
This method should skip the fields without set "inputType" as the default use of it would result in an error, e.g. for field ```id``` or ```tstamp``` which has no input type and thus the exception will be thrown.

https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L392

**Comment by qzminski** [comment]
@Toflar do you agree?

**Comment by Toflar** [comment]
No, you should just not pass the ones that have no `inputType` set. Silent skipping is always bad :)

**Comment by qzminski** [comment]
Then maybe we should state that in the documentation? Currently it's not really obvious and the error like ```Could not find class "" for type ""``` is not that obvious.

**Comment by Toflar** [comment]
I see - the message doesn't really help then. We could throw a different exception? As long as this one is also a `RuntimeException` it's no BC break :)

**Comment by Toflar** [comment]
What about this:

a)
```php
[...]
if (!isset($arrField['type'])) {
    throw new \RuntimeException(sprintf('You did not specify any inputType for the field "%s"!', $strName));
}
[...]
```


b) Add a callback that filters for all the fields that have an `inputType` specified so you don't have to write the same code over and over again but can instead just do:
```php
$form->addFieldsFromDca($table, $hasteBuiltInFilterCallbackName);
```
