### ISSUE TITLE
Add FormDependentMandatoryField to Haste Forms

### ISSUE THREAD

**Issue by christianromeni** [codefog/contao-haste#62]
Hi, I have been trying to add FormDependentMandatoryFields to a haste-generated form.
This does not seem to work.
Is it possible to add support for this? https://github.com/cliffparnitzky/FormDependentMandatoryField

Greets - Christian

**Comment by Toflar** [comment]
This is not a task for haste. This widget only seems to support forms generated using the form generator (using hooks - see https://github.com/cliffparnitzky/FormDependentMandatoryField/blob/master/system/modules/zFormDependentMandatoryField/config/config.php#L33).
