### ISSUE TITLE
Problem with "ondelete_callback"

### ISSUE THREAD

**Issue by baumannsven** [codefog/contao-haste#63]
Hi,
a question regarding the problem of the extentions haste and efg.
 
If these two modules are installed you cannot delete form datas within efg forms.
The reason therefore ist that ondelete_callback 'Haste\Model\Relations', 'cleanRelatedRecords' is called.
To fix this I wanted to ask whether you can do the following step:
Can you insert this code https://github.com/codefog/contao-haste/blob/master/library/Haste/Model/Relations.php#L94 
into this if loop https://github.com/codefog/contao-haste/blob/master/library/Haste/Model/Relations.php#L89?

Thanks Sven

**Comment by Toflar** [comment]
Why? Can you elaborate a bit more? The callback is fine where it is, it is looping over __all__ tables, not only the current one.

**Comment by baumannsven** [comment]
You can close this ticket. I found the problem is near efg as haste.
