### ISSUE TITLE
Set formSubmit value in form->addToObject method

### ISSUE THREAD

**Issue by bezin** [codefog/contao-haste#67]
Hei there, 

is there a reason for not setting the formSubmit value in the addToObject method of Haste\Form\Form like it is set in the generate method? 

Anyhow, I solved the issue by setting that value via $this->hasteInstance->getFormId() in the template, but now I have to do that in every form template.

**Comment by Toflar** [comment]
https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L897 ??

**Comment by bezin** [comment]
Right, I was missing that line here https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L945, but didn't think of yours :) Kiitos!
