### ISSUE TITLE
define classes attributes/fields

### ISSUE THREAD

**Issue by mmiat** [codefog/contao-haste#68]
in backend is it possible to define attributes/fields for classes, so the generated files include them? thanks

**Comment by qzminski** [comment]
?

**Comment by Toflar** [comment]
?

**Comment by mmiat** [comment]
the dca files, it could be useful to create the fields edit, delete, etc. too

**Comment by qzminski** [comment]
@mmiat sorry but I have totally no idea what are you talking about. Can you describe your problem in details and not only with one sentence?

**Comment by mmiat** [comment]
when you create dca file, it contains "config" and "fields", but "list" will be useful too, because it contains the basic operations like "edit", "copy", "delete", and so on

and another useful feature will be the possibility of create the attributes, so not only the default "id", "tstamp" and "title", but the possibility of specify every single attribute

my english is not good but I hope I was clear this time
thanks

**Comment by aschempp** [comment]
Haste\Form is not related to the backend DCA, but only for frontend fields like the form generator.

**Comment by mmiat** [comment]
ok, than it's my fault, I misunderstanding the goal of the project
thanks again and sorry for wasting your time
good work! bye
