### ISSUE TITLE
DateTime::createFromTimestamp does not work properly

### ISSUE THREAD

**Issue by richardhj** [codefog/contao-haste#80]
This is the function:
```php 
    public static function createFromTimestamp($tstamp, \DateTimeZone $timezone=null)
    {
        return static::createFromFormat('U', $tstamp, $timezone);
    }
```
If s.o. calls `::createFromTimestamp()` without the second parameter `$timezone`, your function will call `static::createFromFormat('U', $tstamp, null);`
This leads to a PHP Warning (_DateTime::createFromFormat() expects parameter 3 to be DateTimeZone, null given_).
Even if it's just a warning, the method will return `bool(false)` instead of a `DateTime object`

**Comment by aschempp** [comment]
You're right, the correct solution would be to pass `date_default_timezone_get()` if the argument is `null`

**Comment by richardhj** [comment]
Don't passing `$timezone` is a solution too. Because of the `@date_default_timezone_set(Config::get('timeZone'));` in the `initialize.php`, the right timezone will be applied, wouldn't it?

**Comment by aschempp** [comment]
Correct. Then we would need to if/else the method call.

**Comment by richardhj** [comment]
I have another point belonging to this.
The method returns a `\DateTime` instance, should it not be a `Haste\DateTime\DateTime` instance (to use `getAge()` right from this context)?
This is what it could like:
```php
$objDate = new self();
$objDate->setTimestamp($tstamp);
return $objDate;
```

**Comment by aschempp** [comment]
Sounds reasonable

**Comment by qzminski** [comment]
Should be fixed in 211bc90. Can you confirm?

**Comment by richardhj** [comment]
It works great. Thanks!

**Comment by aschempp** [comment]
The method has just been deprecated. You should simply use `new DateTime('@' . $timestamp)`.
