### ISSUE TITLE
FormExplanation and the getAttributesFromDca function

### ISSUE THREAD

**Issue by stefanheimes** [codefog/contao-haste#83]
Hi, 

i have a problem with the Form::addFormField function. (https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L363)

If I use the FormExplanation Widget, the field need a text value in the dca but in this line: https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L450
you use the getAttributesFromDca which removes this field from the dca. So the FormExplanation won't get the text value. 

A solution would be to merge the result from the ``` $strClass::getAttributesFromDca``` and the current ``` $arrDca ```.

**Comment by stefanheimes** [comment]
Maybe it is a missing function in the contao/core getAttributesFromDca function. But i am not sure.

**Comment by Toflar** [comment]
The code should look like this:

```php
'eval' => ['text' => 'Text explanation']
```

**Comment by stefanheimes** [comment]
You are right. Thx.
