### ISSUE TITLE
Haste Form with datepicker in FE

### ISSUE THREAD

**Issue by lindesbs** [codefog/contao-haste#86]
Is this actually possible ?
```
$objForm->addFormField('modification_date', array(
					'label'         => 'Aenderungsdatum',
					'inputType'     => 'text',
					'value'			=> $modificationTime,
					'eval'          => array('rgxp'=>'datim','datepicker'=>true)
			));
```

**Comment by Toflar** [comment]
No, this is not possible because it's a back end feature. You have to use the "calendarfield" extension that provides a calendarpicker form field for the FE and then use the respective inputType :)
