### ISSUE TITLE
StringUtil::recursiveReplaceTokensAndTags recursion will never stop, if token is not present

### ISSUE THREAD

**Issue by fatcrobat** [codefog/contao-haste#88]
If token is not present in $arrTokens, the recursion will never stop and the php-process will die.

StringUtil::recursiveReplace Line: 81
```
// check if the inserttags have returned a simple token or an insert tag to parse
if ((strpos($strBuffer, '##') !== false || strpos($strBuffer, '{{') !== false) && $strBuffer != $strText) {
    $strBuffer = static::recursiveReplaceTokensAndTags($strBuffer, $arrTokens, $intTextFlags);
}
```

There should be a check for the existence, of the token, that should be replaced.

Thanks for your support.

**Comment by qzminski** [comment]
Can you check if the 05879ee fixes the issue for you?

**Comment by fatcrobat** [comment]
Thanks, can confirm that it is working now.

**Comment by qzminski** [comment]
Sorry @fatcrobat, have you checked my commit explicitly or the 4.14.2 version? The 4.14.2 contains another approach to that fix and not my solution.

**Comment by fatcrobat** [comment]
Did it on 4.14.2 with the old behavior in our Test Environment and got no recursion error.
