### ISSUE TITLE
FR: change 'implode' at 'flatten' to configurable pattern

### ISSUE THREAD

**Issue by zonky2** [codefog/contao-haste#89]
look at https://github.com/codefog/contao-haste/blob/master/library/Haste/Util/StringUtil.php#L193

at different use cases, I need other pattern as ```, ``` e.g. without space after comma or pipe or slash

its possible to change to a more flexible pattern?

**Comment by Toflar** [comment]
Feel free to submit a PR with the implode glue as 4th argument if you really feel like this has to go into haste. You could also just copy the code to your own class and modify it to your needs.

**Comment by zonky2** [comment]
o.k. I´ll try it...

**Comment by qzminski** [comment]
Merged in d317cd91417bdd9b61c860fcca20f32e6588e32f.
