### ISSUE TITLE
Fatal Error from contao-haste/library/Haste/Util/StringUtil.php

### ISSUE THREAD

**Issue by cs1982** [codefog/contao-haste#91]
The following error occurs while completeing an order in my Isotope Shop:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 95 bytes) in /var/www/web28674344/html/dev/composer/vendor/codefog/contao-haste/library/Haste/Util/StringUtil.php on line 92

Following this hint I installed Contao 3.5.18 via Live-Update.
https://community.contao.org/de/showthread.php?64368-Isotope-Fataler-PHP-Error-nach-Update-auf-3-5-17&p=422669&viewfull=1#post422669

Additional I have memory trouble with composer in my environment. This is described here:
https://community.contao.org/de/showthread.php?64368-Isotope-Fataler-PHP-Error-nach-Update-auf-3-5-17&highlight=contao+bestellung+fehler
So I installed haste 4.14.2 manually. Despite manuall update the package management in Contao shows haste-Version 4.11.4

It is not possible to process the Isotope Order without the memory error. I can not locate the error reason (haste/ Contao/ Isotope/ environment) and hope for your overview.

Access to my Contao is no problem, if necessary.

**Comment by cs1982** [comment]
For test I changed php version from 5.6.26 too 7.0.11. Now I have the following error:

Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/web28674344/html/dev/system/modules/core/library/Contao/String.php on line 28

I tried it with haste 4.14.2 an 4.11.4

**Comment by aschempp** [comment]
These are two separate issues. The `String` class has been renamed in the latest Contao version to support PHP 7, but apparently one of your extensions is still using the old name (neither Haste nor Isotope does).

Regarding the memory issue, can you tell me the latest message? Because after you updated the extension I assume the line number has changed.
Also, can you try to remove all content and especially all simple tokens and inserttags from your notification message and try if it works then?

**Comment by cs1982** [comment]
Ok, back to memory error.
I deactivated all content from the site "order notifcation" (Bestellbestätigung im Isotope Modul Kasse). Using haste 4.14.2. Same error occurs:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 2048 bytes) in /var/www/web28674344/html/dev/composer/vendor/codefog/contao-haste/library/Haste/Util/StringUtil.php on line 92

**Comment by cs1982** [comment]
Now I used an empty site layout to eliminate all influence of modules in header and footer.
This error occurs:

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 649 bytes) in /var/www/web28674344/html/dev/composer/vendor/codefog/contao-haste/library/Haste/Util/StringUtil.php on line 112`

**Comment by cs1982** [comment]
Email Notification causes the error. See Community Thread: https://community.contao.org/de/showthread.php?64368-Isotope-Fataler-PHP-Error-nach-Update-auf-3-5-17&p=423001&viewfull=1#post423001
But where i have to solve the issue? Do not use some or all Simple Tokens/ Inserst Tags or is it on development to handle this?

**Comment by cs1982** [comment]
Can I anything do to support?

**Comment by qzminski** [comment]
@cs1982 can you update the haste to 4.14.3 and see if the issue still occurs?

**Comment by cs1982** [comment]
I updated. It works!
Thanks.

2016-12-13 10:09 GMT+01:00 Kamil Kuzminski <notifications@github.com>:
