### ISSUE TITLE
form.html5 does no longer exist

### ISSUE THREAD

**Issue by leofeyer** [codefog/contao-haste#95]
The template `form.html5` does no longer exists in Contao 4.3, therefore the [Form.php](https://github.com/codefog/contao-haste/blob/master/library/Haste/Form/Form.php#L968) class no longer works. The template has been renamed to `form_wrapper.html5`.

In case someone has already updated their installation, there is an easy workaround: create a custom template named `form.html5` and paste the following line:

```php
<?php $this->extend('form_wrapper'); ?>
```

This is not a fix for the issue though. 😄

**Comment by aschempp** [comment]
It would have been a fix to include in Contao 4.3 to keep BC ;-)

Fixed in d258770337908ffb41cee7ac96504f66d324785e
