### ISSUE TITLE
PHP-Fehler bei der Installation

### ISSUE THREAD

**Issue by Schmidty2** [codefog/contao-haste#96]
Ich habe haste in einer bestehenden Installation von Contao 3.5.20 über das ER installiert. Nach der Installation wird nur noch eine leere, weiße Seite angezeigt. Wird die Datei .skip im haste-Verzeichnis abgelegt, funktioniert alles wieder.

Im Error-Log steht folgemder Eintrag:

PHP Fatal error: Class 'Haste\Dca\DateRangeFilter' not found in /is/htdocs/wpXXXXXXXX/www/verzeichnis/system/modules/core/library/Contao/System.php on line 140

Der Contao-Check sagt alles OK
Provider: HostEurope, Webserver Medium,
PHP 5.6.29
Installiert sind das Theme Quantum und CustomCatalog von Premium Contao Themes

**Comment by Tastaturberuf** [comment]
Hört sich an als wäre NamespaceClassLoader nicht (richtig) installiert. Im Modul-Ordner heißt die _autoload.

**Comment by Schmidty2** [comment]
Der NamespaceClassLoader war nicht richtig installiert. Eine Reparaturinstallatiun und alles funktioniert. Danke für den Tipp.
